sudo: false
language: ruby
rvm:
  - 2.6.5
env:
  - ES_VERSION=7.5.0
  - ES_VERSION=7.4.2
  - ES_VERSION=7.3.2
  - ES_VERSION=7.2.1
  - ES_VERSION=7.1.1
  - ES_VERSION=7.0.1
  - ES_VERSION=6.8.5
  - ES_VERSION=6.7.2
  - ES_VERSION=6.6.2
  - ES_VERSION=6.5.4
  - ES_VERSION=6.4.3

before_install: gem install bundler -v 1.16.1
install:
  - if [[ "${ES_VERSION:0:1}" = "7" ]]; then suffix='-linux-x86_64'; else suffix=''; fi
  - download_url=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}${suffix}.tar.gz
  - echo $download_url
  - mkdir -p ./tmp
  - curl $download_url | tar xzmp -C ./tmp
  - ls ./tmp
  - ./tmp/elasticsearch-${ES_VERSION}/bin/elasticsearch &
  - bundle install
  - wget --quiet --waitretry=1 --retry-connrefused --timeout=10 --output-document=- http://127.0.0.1:9200

script: bundle exec rspec
