name: build-os

on: [push]
env:
  ENGINE_NAME: opensearch
  REST_API_SPEC_REPO: opensearch-project/OpenSearch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/opensearch-project/OpenSearch/releases
        search_versions:
        - 1.2.0
        - 1.1.0
        - 1.0.0
    steps:
    - name: Configure sysctl limits
      run: |
        sudo swapoff -a
        sudo sysctl -w vm.swappiness=1
        sudo sysctl -w fs.file-max=262144
        sudo sysctl -w vm.max_map_count=262144
    - name: Runs OpenSearch
      run: docker run -p 9200:9200 -e "discovery.type=single-node" -e "plugins.security.disabled=true" opensearchproject/opensearch:${{matrix.search_versions}}
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - name: Wait for OpenSearch
      run: timeout 60 bash -c "until curl --silent --output /dev/null localhost:9200/_cat/health?h=st; do printf '.'; sleep 5; done; printf '\n'"
    - run: bundle exec rspec
