name: build-os

on: [push]
env:
  ENGINE_NAME: opensearch
  REST_API_SPEC_REPO: opensearch-project/OpenSearch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # https://github.com/opensearch-project/OpenSearch/releases
        search_versions:
          - 3.5.0
          - 3.4.0
          - 3.3.2
          - 3.2.0
          - 3.1.0
          - 3.0.0
    services:
      opensearch:
        image: opensearchproject/opensearch:${{matrix.search_versions}}
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          plugins.security.disabled: true
          OPENSEARCH_INITIAL_ADMIN_PASSWORD: StrongPassword123
    steps:
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Wait for OpenSearch
        run: timeout 120 bash -c "until curl --silent --output /dev/null 'localhost:9200/_cat/health?h=st'; do printf '.'; sleep 5; done; printf '\n'"
      - run: bundle exec rspec
